name: Deploy to AWS EC2

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Get GitHub Runner Public IP
              id: ip
              run: |
                  IP=$(curl -s http://checkip.amazonaws.com)
                  echo "runner_ip=$IP/32" >> $GITHUB_OUTPUT

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Authorize GitHub Runner IP in Security Group
              run: |
                  aws ec2 authorize-security-group-ingress \
                    --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
                    --protocol tcp \
                    --port 22 \
                    --cidr ${{ steps.ip.outputs.runner_ip }}

            - name: Login to AWS ECR
              run: |
                  aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
                  docker login --username AWS --password-stdin \
                  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            - name: Build and Tag Docker Image
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }} .
                  docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
                  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

            - name: Push Docker Image to ECR
              run: |
                  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      docker login -u AWS -p $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
                      docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

                    
                      if [ $(docker ps -a -q -f name=apc) ]; then
                        docker stop apc
                        docker rm apc
                      fi

                      # Run the latest image
                      docker run -d --name apc --env-file /home/ec2-user/admin-panel.env --network host \
                        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest


                      # Get the image ID of the one just used
                      IMAGE_ID=$(docker images --format "{{.Repository}} {{.Tag}} {{.ID}}" | grep "${{ secrets.ECR_REPOSITORY }} latest" | awk '{print $3}')

                      # Remove all other images except the latest one
                      docker images -q | grep -v "$IMAGE_ID" | xargs -r docker rmi -f

                      echo "✅ Old images cleaned up!"



            - name: Revoke GitHub Runner IP from Security Group
              if: always()
              run: |
                aws ec2 revoke-security-group-ingress \
                  --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
                  --protocol tcp \
                  --port 22 \
                  --cidr ${{ steps.ip.outputs.runner_ip }}